# parameters for Maximum allowed Cartesian Velocity when in Cartesian Impedance
# the values are divided into translational and rotational
# each of the translational and rotational components is defined as Vector3
# for more info on Vector3 messages please see the following link:
# http://docs.ros.org/api/geometry_msgs/html/msg/Vector3.html

# trans: [mm/s]
geometry_msgs/Vector3 translational

#rot: [rad/s]
geometry_msgs/Vector3 rotational
