# parameters for Maximum allowed Cartesian Velocity when in Cartesian Impedance
# the values are divided into translational and rotational
# the overall message is defined as Twist.
# The Twist message is composed of:
#  1. geometry_msgs/Vector3 linear
#  2. geometry_msgs/Vector3 angular

# for more info on Twist messages please see the following link:
# http://docs.ros.org/api/geometry_msgs/html/msg/Twist.html

# Vector3 message info:
# http://docs.ros.org/api/geometry_msgs/html/msg/Vector3.html

# trans: [m/s]
# rotation: [rad/s]
geometry_msgs/Twist set
